version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - 1338:80
    depends_on:
      - web
    networks:
      - app

  db:
    image: mysql:8.0.31
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'mentiz'
       MYSQL_USER: 'mentiz'
       MYSQL_PASSWORD: 'mentiz'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - data:/var/lib/mysql
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    volumes:
      - .:/mentiz
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge

volumes:
  data: